"""Checked-in execution captures for the hosted evidence explorer."""

from importlib.resources import files

from cross_examine.codec import report_from_json
from cross_examine.schema import Report
from cross_examine.validation import validate_report


def broken_fixture_report() -> Report:
    """Load the real hero-pipeline capture generated by the companion script."""

    capture = files("cross_examine.fixture_data").joinpath("broken.json")
    return validate_report(report_from_json(capture.read_text(encoding="utf-8")))
